### ISSUE TITLE
Wasn't able to import my Polar

### ISSUE THREAD

**Issue by caspartfg** [htool/signalk-polar-performance-plugin#1]
I got the following error when trying to import:

error starting plugin: TypeError: polar.forEach is not a function

(i've attached my polar for reference). I tested the polar on https://jieter.github.io/orc-data/site/#customplot and it rendered without an issue.

[n40-polar.csv](https://github.com/htool/signalk-polar-performance-plugin/files/11464076/n40-polar.csv)

**Comment by htool** [comment]
That first row and last column seem off.
Could you try with out them?

**Comment by caspartfg** [comment]
Hi Hans, thanks for replying so quickly. I've tried and still have the same issue...  updated polar attached and the error I am still getting.

really looking forward to getting this working with my B&G Zeus3 (got your other plugins working perfectly).

May 12 14:13:43 2023-05-12T14:13:43.354Z signalk-polar-performance-plugin Plugin started
May 12 14:13:43 2023-05-12T14:13:43.356Z signalk-polar-performance-plugin Options: {"useSOG":true,"csvTable":"/data/conf/signalk/plugin-config-data/n40-polar.csv"}
May 12 14:13:43 error starting plugin: TypeError: polar.forEach is not a function
May 12 14:13:43 TypeError: polar.forEach is not a function at csvToPolarObject (/data/conf/signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:460:13) at Object.plugin.start (/data/conf/signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:67:17) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:264:20) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:418:21 at savePluginOptions (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:131:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:405:13 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:144:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:114:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at Function.handle (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:175:3) at router (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5)

[n40-polar.csv](https://github.com/htool/signalk-polar-performance-plugin/files/11464960/n40-polar.csv)

**Comment by htool** [comment]
Ah :) I need to make that clearer as you're not the first.
Cooy-paste the content of the csv in there, not the filename.

**Comment by caspartfg** [comment]
Ooops :-)   no worries, could just be my poor reading of the instructions......

I've now got the following error:

May 12 15:04:24 2023-05-12T15:04:24.485Z signalk-polar-performance-plugin Plugin started
May 12 15:04:24 2023-05-12T15:04:24.488Z signalk-polar-performance-plugin Options: {"useSOG":true,"csvTable":"twa/tws;0;4;6;8;10;12;16;20;24;30;60\n45;0.00;1.67;2.54;3.39;4.19;4.90;6.00;6.96;7.06;6.72\n50;0.00;2.12;3.15;4.12;4.99;5.78;7.26;8.03;8.33;8.47\n60;0.00;2.41;3.55;4.59;5.51;6.37;7.91;8.90;9.35;9.66\n70;0.00;3.16;4.57;5.79;6.92;7.92;9.07;9.85;10.50;11.03\n80;0.00;3.34;4.79;6.05;7.21;8.22;9.81;10.60;11.62;12.36\n90;0.00;3.38;4.83;6.10;7.26;8.27;10.32;11.45;12.66;13.59\n100;0.00;3.29;4.71;5.95;7.10;8.11;10.09;12.20;13.43;14.75\n110;0.00;3.09;4.48;5.71;6.85;7.89;9.61;11.83;14.23;14.25\n120;0.00;2.92;4.26;5.45;6.56;7.59;8.96;10.84;13.76;13.09\n135;0.00;2.57;3.78;4.90;5.93;6.91;7.94;9.49;11.71;11.65\n150;0.00;2.16;3.21;4.21;5.14;6.02;7.09;8.50;10.32;10.68\n165;0.00;1.89;2.82;3.73;4.59;5.40;6.48;7.84;9.46;10.17\n180;0.00;1.76;2.63;3.48;4.30;5.08;5.94;7.22;8.71;10.09"}
May 12 15:04:24 2023-05-12T15:04:24.491Z signalk-polar-performance-plugin polar: [{"tws":0},{"tws":2.057782533541855},{"tws":3.086673800312783},{"tws":4.11556506708371},{"tws":5.144456333854638},{"tws":6.173347600625566},{"tws":8.23113013416742},{"tws":10.288912667709276},{"tws":12.346695201251132},{"tws":15.433369001563914},{"tws":30.86673800312783}]
May 12 15:04:24 error starting plugin: TypeError: Cannot read property 'sort' of undefined
May 12 15:04:24 TypeError: Cannot read property 'sort' of undefined at /data/conf/signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:462:29 at Array.forEach (<anonymous>) at csvToPolarObject (/data/conf/signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:460:13) at Object.plugin.start (/data/conf/signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:67:17) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:264:20) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:418:21 at savePluginOptions (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:131:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:405:13 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:144:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:114:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at Function.handle (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:175:3)

**Comment by htool** [comment]
Comma seperation is needed, not semi :)

**Comment by caspartfg** [comment]
cool - thanks Hans, I tried commas, but still seeing errors...

btw, as a bit of context the site you referenced in your instructions insists on a semi-colon, rather than a comma, so I changed the formatting to match....

have you got an known good polar I could try?

current error log:

May 12 15:49:43 2023-05-12T15:49:43.359Z signalk-polar-performance-plugin Plugin started
May 12 15:49:43 2023-05-12T15:49:43.363Z signalk-polar-performance-plugin Options: {"useSOG":true,"csvTable":"twa/tws,0,4,6,8,10,12,16,20,24,30,60\n45,0.00,1.67,2.54,3.39,4.19,4.90,6.00,6.96,7.06,6.72\n50,0.00,2.12,3.15,4.12,4.99,5.78,7.26,8.03,8.33,8.47\n60,0.00,2.41,3.55,4.59,5.51,6.37,7.91,8.90,9.35,9.66\n70,0.00,3.16,4.57,5.79,6.92,7.92,9.07,9.85,10.50,11.03\n80,0.00,3.34,4.79,6.05,7.21,8.22,9.81,10.60,11.62,12.36\n90,0.00,3.38,4.83,6.10,7.26,8.27,10.32,11.45,12.66,13.59\n100,0.00,3.29,4.71,5.95,7.10,8.11,10.09,12.20,13.43,14.75\n110,0.00,3.09,4.48,5.71,6.85,7.89,9.61,11.83,14.23,14.25\n120,0.00,2.92,4.26,5.45,6.56,7.59,8.96,10.84,13.76,13.09\n135,0.00,2.57,3.78,4.90,5.93,6.91,7.94,9.49,11.71,11.65\n150,0.00,2.16,3.21,4.21,5.14,6.02,7.09,8.50,10.32,10.68\n165,0.00,1.89,2.82,3.73,4.59,5.40,6.48,7.84,9.46,10.17\n180,0.00,1.76,2.63,3.48,4.30,5.08,5.94,7.22,8.71,10.09"}
May 12 15:49:43 error starting plugin: TypeError: polar.forEach is not a function
May 12 15:49:43 TypeError: polar.forEach is not a function at csvToPolarObject (/data/conf/signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:460:13) at Object.plugin.start (/data/conf/signalk/node_modules/signalk-polar-performance-plugin/plugin/index.js:67:17) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:264:20) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:418:21 at savePluginOptions (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:131:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:405:13 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:144:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:114:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at Function.handle (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:175:3) at router (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5)

**Comment by htool** [comment]
Not behind computer now. I used one from the site for oceanis 40. Can you try to remove the 0 column?

**Comment by htool** [comment]
Sorry,  ; is fine. 0 column I think causes the problem.

**Comment by caspartfg** [comment]
yup, that sorted it.... I cross-ref'd with the other polar file.....
two issues were that the  'slash' in twa/tws was the wrong way around and there was an extra '0' column,
weirdly I generated the polar in OpenCPN, so it's strange the format didn't marry-up. Anyway, looks like the plug-in is working now... job tomorrow is to hook it up with the B&G.... Thanks Hans, really appreciate it!!!

CSV for reference:

twa/tws;4;6;8;10;12;16;20;24;30;60
0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00;0.00
45;0.00;1.67;2.54;3.39;4.19;4.90;6.00;6.96;7.06;6.72
50;0.00;2.12;3.15;4.12;4.99;5.78;7.26;8.03;8.33;8.47
60;0.00;2.41;3.55;4.59;5.51;6.37;7.91;8.90;9.35;9.66
70;0.00;3.16;4.57;5.79;6.92;7.92;9.07;9.85;10.50;11.03
80;0.00;3.34;4.79;6.05;7.21;8.22;9.81;10.60;11.62;12.36
90;0.00;3.38;4.83;6.10;7.26;8.27;10.32;11.45;12.66;13.59
100;0.00;3.29;4.71;5.95;7.10;8.11;10.09;12.20;13.43;14.75
110;0.00;3.09;4.48;5.71;6.85;7.89;9.61;11.83;14.23;14.25
120;0.00;2.92;4.26;5.45;6.56;7.59;8.96;10.84;13.76;13.09
135;0.00;2.57;3.78;4.90;5.93;6.91;7.94;9.49;11.71;11.65
150;0.00;2.16;3.21;4.21;5.14;6.02;7.09;8.50;10.32;10.68
165;0.00;1.89;2.82;3.73;4.59;5.40;6.48;7.84;9.46;10.17
180;0.00;1.76;2.63;3.48;4.30;5.08;5.94;7.22;8.71;10.09

**Comment by caspartfg** [comment]
Hi Hans, not sure if you want it posted here or somewhere else, but I can't seem to link the performance polar plugin with the B&G PGN plugin. 

Could well be use error on my part, but I thought these paths would be available to pass through to B&G?
May 16 07:03:47 2023-05-16T07:03:47.796Z signalk-bandg-performance-plugin path: performance.targetAngle value: undefined
May 16 07:03:48 2023-05-16T07:03:48.390Z signalk-bandg-performance-plugin path: performance.polarSpeed value: undefined
May 16 07:03:48 2023-05-16T07:03:48.392Z signalk-bandg-performance-plugin path: performance.polarSpeedRatio value: undefined

Any suggestions? the Polar Plugin seems to be working and I can see my Polar details as a webapp within SignalK

Thanks

Casp.

**Comment by htool** [comment]
Do you see performance data in the data browser?

I may need to add interpolation below the lowest polar line to give numbers while docked as that may be when people try out the settings.

**Comment by caspartfg** [comment]
hi Hans, nope, there isn't anything in the data browser....
I'm actually out sailing at the moment up the coast of Sardinia - 15 knots of wind....

**Comment by caspartfg** [comment]
update - managed to fix it - I was missing "environment.wind.angleTrueWater" is now being generated through derived data.... sorry about that.   the Polar data is now showing up in the data browser... will now  play around with the B&G
