### ISSUE TITLE
feature request: percentage weighting on polar

### ISSUE THREAD

**Issue by caspartfg** [htool/signalk-polar-performance-plugin#2]
This is an awesome plug-in and just what i'd been looking for. We live aboard our boat and have a B&G setup with an extensive N2K & ethernet marine network.

One request I would like - I'd like to be able to apply a "percentage weighting" to my target polar speeds (and calculations). We're quite a heavy boat (with all our 'stuff' onboard), so can't achieve the factory polars..... When it comes to passage planning, I assume around 90% of what our polar says should be achievable.  It would be awesome I could apply that same weighting in the plug-in so I can keep that same consistency (rather than modifying the polar itself).

the "performance adjustment" feature in FastSeas is a good example of what i'd love to have:  https://fastseas.com/

**Comment by htool** [comment]
In there in 0.0.27. Let me know if that works. You can see the effect in the polar webapp.

**Comment by caspartfg** [comment]
wow, that was quick, but...

have installed 0.0.27, can see the feature but.....

1) it doesn't seem to make a difference, setting it to 0.8, the polar stays the same in the webapp.
2) something is happened to the B&G integration as the Zeus3 is not able to show the values now.

**Comment by htool** [comment]
1. SignalK restart is needed to make it work. Webapp should then show the new values.
2. I assume that will be fixed then as well.

**Comment by caspartfg** [comment]
Perfect - thanks!!!!
FYI - took 2 x reboots of SignalK, one to install v. 0.0.27 and one to get the 0.9 factor to apply.
On the B&G plugin, after the update I had to go back in to the Zeus3 settings and re-enable the Signalk(123456) as a source for it to work.

Thanks Hans, you're a super star!!!!
